[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM3
monitor_port = COM3

lib_deps = 
    adafruit/Adafruit SHT4x Library
    adafruit/Adafruit VEML6075 Library
    adafruit/Adafruit Unified Sensor
